### ISSUE TITLE
Issues with returning result variables

### ISSUE THREAD

**Issue by ghost** [vorticalbox/Pymark#7]
Hi,
I'm playing around with making a GUI in WxPython as I mentioned in my discord.

One area where I'm running into issues is getting values for the results in Pythagoras.py.

Could you add a way to return the variables for each of the results?

Thanks.

**Comment by edwinamoo8** [comment]
Am new to terraform and building a web infrastructure using this link : 

https://hackernoon.com/manage-aws-vpc-as-infrastructure-as-code-with-terraform-55f2bdb3de2a


Error: resource 'aws_instance.wb' config: unknown resource 'aws_security_group.sgweb' referenced in variable aws_security_group.sgweb.id
